### PR TITLE
routes and models are modified to accommodate favorite

### PR DESCRIPTION
**Pull request by ssr8998**
------------------------------------------------------------------
new model in models.py
------------------------------------------------------------------
[1] FavoriteSupplier
	- this will contain favorite suppliers
	- a new table will be created in DB
	- columns are: id, supplier_id
------------------------------------------------------------------
new test cases in test_models.py
------------------------------------------------------------------
[1] test_element_in_add_favorite
	- it will test if a supplier is added successfully in the list
[2] test_get_all_favorite_supplier
	- it will test if loading all favorite suppliers works
------------------------------------------------------------------
new test cases in test_routes.py
------------------------------------------------------------------
[1] test_add_supplier_in_favorite_list
	- it will test if a supplier is added successfully in the list
[2]	test_get_favorite_suppliers
	- it will test if loading all favorite suppliers works

### CODE REVIEW

**Comment by joyceluyy** [comment]
@ssr8998 Hi Sayed, I see you create another table for the favorite supplier. But seems in that table it is just mapping the supplier id from the main table to another set of supplier id in the "favorite_suppliers" table. In that case can't favorite supplier be an attribute in the main table? 

And I am wondering if favorite supplier should be user specific meaning the data should not stored on the server side but client side? like in the cookie?

**Comment by snr6450** [comment]
I was wondering the same as @joyceluyy . But do we have any sample code  from professor to see how one stores data in cookies? That would be helpful

**Comment by joyceluyy** [comment]
Yeah, if we decide to present the same info to all clients, I think it might be easier if we can keep everything in the same table. Like using the top rated supplier as the favorite supplier?

**Comment by ssr8998** [comment]
I think we all came from different design background and there are multiple way to solve a problem and not a single approach is the one and only way to think to  solve  problem , as far as the business logic is working we should be fine .

**Comment by snr6450** [comment]
@ssr8998 I noticed the test coverage for main is at 96% and with this favorites branch it falls to 93%..Could you pls find a way to increase that? We can keep the logic as is no problem

**Comment by joyceluyy** [comment]
@ssr8998 If you really want to keep two tables, I think you will need to rewrite all the test functions for all the class functions you crated for create, update, delete, serialize and deserialize the new table, similar to what we did in the model and model test.

**Comment by ssr8998** [comment]
another branch is created to accommodate more test cases .

**Pull request closed without merging**
